### ISSUE TITLE
Env Canada buoys not in CoastWatch ERDDAP

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/buoy_barn#287]
Buoys 44137, 44150 and 44258 are not in the NOAA CoastWatch ERDDAP. 

But I did find the IOOS.us ERDDAP server which has all of the environment canada buoys and a few more in our region we may want to investigate:
http://erddap.sensors.ioos.us/erddap/tabledap/ca_weather_44137.html
http://erddap.sensors.ioos.us/erddap/tabledap/ca_weather_44150.html
http://erddap.sensors.ioos.us/erddap/tabledap/ca_weather_44258.html

Further east env canada buoys:
http://erddap.sensors.ioos.us/erddap/tabledap/ca_weather_44139.html
http://erddap.sensors.ioos.us/erddap/tabledap/ca_weather_44144.html

There are A LOT of USGS river gauges on this ERDDAP server!

**I did notice it's an older version of ERDDAP (tell tale purple background on graph)

**Comment by youngmorse** [comment]
I thought I had disabled the wonky Env Canada buoys from the IOOS ERDDAP, but Tom noticed Banquereau Banks (it's way out in the Cabot Strait) was still active and wondered where we were getting that data. Since I had already set up 44137 and 44150 (East Scotia Slope and La Have Bank), I reactivated them, but they didn't update with recent data as I had thought they might after 15-20 minutes. I just deactivated 44137 and 44150, but 44139 is now hung up on 2/10/21 (no recent data). 
The IOOS ERDDAP  has been updated to 2.02 by Axiom and now has some 38k datasets in it, so it seems like it's grown up a bit from when I first created this issue. There is still something off with how that ERDDAP and associated datasets are configured in Buoy Barn, but they are reporting recent data. http://erddap.sensors.ioos.us/erddap/search/index.html?page=1&itemsPerPage=1000&searchFor=environment+canada

**Comment by abkfenris** [comment]
Debugging Gist: https://gist.github.com/abkfenris/fe3b973f799902d8513c8e00cb823fad 

It looks like the IOOS Sensor ERDDAP is returning times in reverse order from all the other ERDDAP servers that I've tested Buoy Barn against. Because I'm picking the last row from the dataframe, it's giving me the first value rather than the last value that I expect.
