### ISSUE TITLE
Need new data types in Buoy Barn for 'other' data types (oa, biological, chemical)

### ISSUE THREAD

**Issue by youngmorse** [gulfofmaine/buoy_barn#350]
We need to add some new data types to BB to accommodate the sensors measuring ocean acidification, chemical, and biological data. There are some close matches in BB already, but the units aren't matching up to what we are being served by the data providers. Used the [CF Standard Name Table](http://cfconventions.org/Data/cf-standard-names/77/build/cf-standard-name-table.html) to try and match.

Here is a best first start at matching all the 'other' data we have from UNH:

Appledore Island CO2 buoy ([http://www.neracoos.org/erddap/tabledap/UNH_WBD.html](http://www.neracoos.org/erddap/tabledap/UNH_WBD.html)): 
* Chlorophyll, conductivity and turbidity are good 
* co2_a 
   * units = ppm, 
   * standard_name in ERDDAP = xco2_a 
  * long_name in ERDDAP: Atmospheric_mole_fraction_carbon_dioxide
   * CF standard name to add: The closest is `mole_concentration_of_carbon_dioxide_in_air` but the units are mol m-3, and I think we need mole_fraction which isn't an option. 

* co2_w
   * units = ppm, 
   * standard_name in ERDDAP = xco2_w   
   *  long_name in ERDDAP: Mole_fraction_carbon_dioxide_in_water
   * CF standard name to add: there isn’t a good match for mole fraction/concentration in seawater (similar to above for co2_a)

* oxygen
    * units = uM/kg 
    * standard_name in ERDDAP = mole_concentration_of_dissolved_molecular_oxygen_in_sea_water
    * none of the BB data types have a microM  for oxygen     
    * closest match on CF - moles_of_oxygen_per_unit_mass_in_sea_water (m/kg)

CML - Coastal Marine Lab ([http://www.neracoos.org/erddap/tabledap/UNH_CML.html](http://www.neracoos.org/erddap/tabledap/UNH_CML.html)):

* Chlorophyll, pH, total alkalinity are good

* oxygen
    * units = uM/kg 
    * standard name in ERDDAP = mole_concentration_of_dissolved_molecular_oxygen_in_sea_water
    * none of the BB data types have a microM  for oxygen     
    * closest match on CF - moles_of_oxygen_per_unit_mass_in_sea_water (m/kg)

* co2_w
   * units = ppm, 
   * standard_name in ERDDAP = xco2_w   
   * long_name in ERDDAP: Mole_fraction_carbon_dioxide_in_water
   * CF standard name to add: there isn’t a good match for mole fraction/concentration in seawater     

* omega_a
   * units = just a value (like pH) 
   * standard_name in ERDDAP = omega_a
   * long_name in ERDDAP = omega_aragonite-derived from total alkalinity and pCO2
   * match on CF - no match for omega_a 
   
* omega_c
   * units = just a value (like pH) 
   * long_name in ERDDAP = omega_calcite-derived from total alkalinity and pCO2
   * standard_name in ERDDAP = omega_c
   * match on CF - no match for omega_c

Side note: in some cases, the standard names don't align with the right CF in ERDDAP but the data as described match existing data types in BB or other CF standards.

**Comment by abkfenris** [comment]
Ok, how about these standard names, short names, long names, and units (see inlined):

> Appledore Island CO2 buoy (http://www.neracoos.org/erddap/tabledap/UNH_WBD.html): 
> 
>     * Chlorophyll, conductivity and turbidity are good
> 
>     * co2_a
>       
>       * units = ppm,
>       * standard_name in ERDDAP = xco2_a
>       * long_name in ERDDAP: Atmospheric_mole_fraction_carbon_dioxide
>       * CF standard name to add: The closest is `mole_concentration_of_carbon_dioxide_in_air` but the units are mol m-3

- 'Standard Name' - `mole_concentration_of_carbon_dioxide_in_air_ppm`
- Short Name - "PPM Atmospheric Carbon Dioxide"
- Long Name - "Atmospheric Concentration of Carbon Dioxide in Parts Per Million",
- Units - `ppm`

>     * co2_w
>       
>       * units = ppm,
>       * standard_name in ERDDAP = xco2_w
>       * long_name in ERDDAP: Mole_fraction_carbon_dioxide_in_water
>       * CF standard name to add: there isn’t a good match for mole fraction/concentration in seawater

- 'Standard Name' - `surface_partial_pressure_of_carbon_dioxide_in_sea_water_ppm`?
- Short Name - "PPM Sea Water Carbon Dioxide"
- Long Name - "Sea Water Concentration of Carbon Dioxide in Parts Per Million"
- Units - `ppm`

>     * oxygen
>       
>       * units = uM/kg
>       * standard_name in ERDDAP = mole_concentration_of_dissolved_molecular_oxygen_in_sea_water
>       * none of the BB data types have a microM  for oxygen
>       * closest match on CF - moles_of_oxygen_per_unit_mass_in_sea_water (m/kg)

- 'Standard Name' - `moles_of_oxygen_per_unit_mass_in_sea_water_um_kg'
- Short Name - 'uM Oxygen per kg Sea Water
- Long Name - 'Micro Moles Oxygen per Kilogram of Sea Water'
- Units - `uM/kg`

> CML - Coastal Marine Lab (http://www.neracoos.org/erddap/tabledap/UNH_CML.html):
> 
>     * Chlorophyll, pH, total alkalinity are good
> 
>     * oxygen
>       
>       * units = uM/kg
>       * standard name in ERDDAP = mole_concentration_of_dissolved_molecular_oxygen_in_sea_water
>       * none of the BB data types have a microM  for oxygen
>       * closest match on CF - moles_of_oxygen_per_unit_mass_in_sea_water (m/kg)

See above

> 
>     * co2_w
>       
>       * units = ppm,
>       * standard_name in ERDDAP = xco2_w
>       * long_name in ERDDAP: Mole_fraction_carbon_dioxide_in_water
>       * CF standard name to add: there isn’t a good match for mole fraction/concentration in seawater

Same as above

>     * omega_a
>       
>       * units = just a value (like pH)
>       * standard_name in ERDDAP = omega_a
>       * long_name in ERDDAP = omega_aragonite-derived from total alkalinity and pCO2
>       * match on CF - no match for omega_a

- 'Standard Name' - `omega_aragonite`
- Short Name - 'Omega Aragonite'
- Long Name - 'Omega Aragonite - Derived from total alkalinity and pCO2'
- - Units - `Omega`
 
>     * omega_c
>       
>       * units = just a value (like pH)
>       * long_name in ERDDAP = omega_calcite-derived from total alkalinity and pCO2
>       * standard_name in ERDDAP = omega_c
>       * match on CF - no match for omega_c


- 'Standard Name' - `omega_calcite`
- Short Name - 'Omega Calcite'
- Long Name - 'Omega Calcite - Derived from total alkalinity and pCO2'
- Units - `Omega`

**Comment by youngmorse** [comment]
This looks good @abkfenris  The units are most important for MD and as long as we are describing the data in the long name field we can can modify any standard names down the road if a better option turns up. In my research I found an ERDDAP for [NOAA PMEL](https://www.pmel.noaa.gov/) program (they manage a lot of climate/carbonate data) but the standard names are inconsistent for the carbonate data. [https://data.pmel.noaa.gov/pmel/erddap/index.html](https://data.pmel.noaa.gov/pmel/erddap/index.html)

**Comment by abkfenris** [comment]
@youngmorse The standard names are actually the parts that are more fixed in our data structure. We can always change what standard_name is connected to a timeseries though.

**Comment by abkfenris** [comment]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/1296209/115289569-b73a2a80-a120-11eb-8844-643824c65458.png">

Local test works. Sentry will throw a few errors about unknown data type, but it will just pass it through with no conversions. I'll get it live on Buoy Barn, and then update Mariners so it doesn't complain.

**Comment by abkfenris** [comment]
Data types deployed to Buoy Barn https://github.com/gulfofmaine/buoy_barn/actions/runs/764711633
